# Generated by Django 4.2.1 on 2023-08-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fileupload", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileupload",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="raster_files"),
        ),
    ]
