# Generated by Django 4.2.1 on 2023-08-12 03:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fileupload", "0002_alter_fileupload_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileupload",
            name="fileEdited",
            field=models.FileField(blank=True, null=True, upload_to="edited_file"),
        ),
    ]
